// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "first_name", Type: field.TypeString},
		{Name: "last_name", Type: field.TypeString},
		{Name: "user_name", Type: field.TypeString},
		{Name: "waste_limit", Type: field.TypeUint64, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_id",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[0]},
			},
		},
	}
	// WastesColumns holds the columns for the "wastes" table.
	WastesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "cost", Type: field.TypeInt64},
		{Name: "category", Type: field.TypeString},
		{Name: "date", Type: field.TypeTime},
		{Name: "user_wastes", Type: field.TypeInt64, Nullable: true},
	}
	// WastesTable holds the schema information for the "wastes" table.
	WastesTable = &schema.Table{
		Name:       "wastes",
		Columns:    WastesColumns,
		PrimaryKey: []*schema.Column{WastesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "wastes_users_wastes",
				Columns:    []*schema.Column{WastesColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "waste_category",
				Unique:  false,
				Columns: []*schema.Column{WastesColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
		WastesTable,
	}
)

func init() {
	WastesTable.ForeignKeys[0].RefTable = UsersTable
}
