// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/google/uuid"
	"gitlab.ozon.dev/stepanov.ao.dev/telegram-bot/internal/ent/schema"
	"gitlab.ozon.dev/stepanov.ao.dev/telegram-bot/internal/ent/waste"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	wasteFields := schema.Waste{}.Fields()
	_ = wasteFields
	// wasteDescID is the schema descriptor for id field.
	wasteDescID := wasteFields[0].Descriptor()
	// waste.DefaultID holds the default value on creation for the id field.
	waste.DefaultID = wasteDescID.Default.(func() uuid.UUID)
}
