-- create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "first_name" character varying NOT NULL, "last_name" character varying NOT NULL, "user_name" character varying NOT NULL, PRIMARY KEY ("id"));
-- create "wastes" table
CREATE TABLE "wastes" ("id" uuid NOT NULL, "cost" bigint NOT NULL, "category" character varying NOT NULL, "date" timestamptz NOT NULL, "user_wastes" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "wastes_users_wastes" FOREIGN KEY ("user_wastes") REFERENCES "users" ("id") ON DELETE SET NULL);
