// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package requests

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson59e4e729DecodeGitlabOzonDevStepanovAoDevTelegramBotInternalModelsRequests(in *jlexer.Lexer, out *GetReport) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "user_id":
			out.UserID = int64(in.Int64())
		case "period":
			out.Period = Period(in.Int())
		case "currency_exchange":
			out.CurrencyExchange = float64(in.Float64())
		case "currency_designation":
			out.CurrencyDesignation = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson59e4e729EncodeGitlabOzonDevStepanovAoDevTelegramBotInternalModelsRequests(out *jwriter.Writer, in GetReport) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.UserID))
	}
	{
		const prefix string = ",\"period\":"
		out.RawString(prefix)
		out.Int(int(in.Period))
	}
	{
		const prefix string = ",\"currency_exchange\":"
		out.RawString(prefix)
		out.Float64(float64(in.CurrencyExchange))
	}
	{
		const prefix string = ",\"currency_designation\":"
		out.RawString(prefix)
		out.String(string(in.CurrencyDesignation))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetReport) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson59e4e729EncodeGitlabOzonDevStepanovAoDevTelegramBotInternalModelsRequests(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetReport) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson59e4e729EncodeGitlabOzonDevStepanovAoDevTelegramBotInternalModelsRequests(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetReport) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson59e4e729DecodeGitlabOzonDevStepanovAoDevTelegramBotInternalModelsRequests(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetReport) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson59e4e729DecodeGitlabOzonDevStepanovAoDevTelegramBotInternalModelsRequests(l, v)
}
