global:
  scrape_interval: 2s
  scrape_timeout: 2s
  evaluation_interval: 1s # Evaluate rules

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]

  - job_name: "telegram-bot"
    static_configs:
      - targets: ["telegram-bot:3000"]

  - job_name: "report-service"
    static_configs:
      - targets: ["report-service:3000"]
